### ISSUE TITLE
Warning: Deprecated: mysql_connect()

### ISSUE THREAD

**Issue by HumaMilisic** [etf-sarajevo/zamger#1]
#### Uslovi:
- WAMPSERVER 2.5
- PHP 5.5.12
- MYSQL 5.6.17
- APACHE 2.4.9
#### Warning:

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\wamp\www\zamger\lib\libvedran.php on line 54
##### Call Stack

| br | Time | Memory | Function | Location |
| --- | --- | --- | --- | --- |
| 1 | 0.0008 | 335080 | {main}( ) | ..\index.php:0 |
| 2 | 0.0042 | 808376 | dbconnect2( ) | ..\index.php:70 |
| 3 | 0.0042 | 808568 | mysql_connect ( ) | ..\libvedran.php:54 |

**Comment by vljubovic** [comment]
6be9ddd
