### ISSUE TITLE
Bug, Pretraga osoba

### ISSUE THREAD

**Issue by HumaMilisic** [etf-sarajevo/zamger#2]
#### Uslovi:
- WAMPSERVER 2.5
- PHP 5.5.12
- MYSQL 5.6.17
- APACHE 2.4.9
#### Koraci:
1. login kao admin
2. otvoriti studentsku sluzbu
3. otvoriti osobe
4. unijeti nesto u pretragu osoba, pritisnuti pretrazi
##### Rezultat

MYSQL query:

`select id,ime,prezime,brindexa,naucni_stepen from osoba where (ime like '%gg%' or prezime like '%gg%' or brindexa like '%gg%' ) order by prezime,ime limit 0,20`

MYSQL error:

`Unknown column 'naucni_stepen' in 'field list'`

**Comment by vljubovic** [comment]
Popravljeno (prije godinu i po), 111b7615b68f2b422238559eae0fc8bb016e08b7
