### ISSUE TITLE
Zamijenjeni predmeti, prilikom kreiranja ugovora o ucenju, za telekomunikacije i ri MSc druga godina

### ISSUE THREAD

**Issue by mirhat** [etf-sarajevo/zamger#21]
I ugovor o ucenju je pogresan

**Comment by vljubovic** [comment]
Prilikom kreiranja ugovora o učenju treba izabrati studij "Telekomunikacije (MSc)"

**Comment by vljubovic** [comment]
![babicm](https://cloud.githubusercontent.com/assets/1290105/23204071/612183ba-f8e5-11e6-89b3-52bd6719ebce.png)
