### ISSUE TITLE
Podrška za mobilnost

### ISSUE THREAD

**Issue by vljubovic** [etf-sarajevo/zamger#22]
Trenutno u Zamgeru ne postoji podrška za gostujuće studente koji dolaze na studij po osnovu mobilnosti. Ovo se za sada rješava forsiranjem upisa na odgovarajući semestar. Potrebno je provjeriti važeća pravila (ne postoji univerzitetski pravilnik o mobilnosti ali postoji fakultetski).

**Comment by vljubovic** [comment]
U suštini ovo se svodi na dvije stvari:
* korisnički interfejs da se može unijeti izvještaj o mobilnosti
* u takvim situacijama prihvatiti upis na višu godinu iako student nije položio sve obavezne predmete, ali ima potreban broj ECTS kredita

**Comment by tsijercic1** [comment]
1. Student kojem se priznaje mora biti registrovan na zamgeru prije priznavanja. Dakle, treba da ima sve podatke(na bazi) kao i ostali studenti. Da/Ne?
2. Šta je tačno akademska godina u odnosu na ovo priznavanje?
3. Naziv predmeta i šifra predmeta te ects su polja za predmet koji je student položio u stranoj ustanovi. Da/Ne?
4. Ocjena se veže za predmet s našeg fakulteta. Da/Ne?

**Comment by vljubovic** [comment]
1. Da.
2. Akademska godina u kojoj je student bio na mobilnosti. Npr. student je u oktobru 2018. otišao u Malardalen i tamo ispolagao neke ispite, vratio se na proljeće. Ocjene će biti evidentirane kao stečene u akademskoj 2018/2019. godini.
3. Da
4. Ne. To je razlika između mobilnosti (priznavanje) i ekvivalencije. Procedura za ekvivalenciju je drugačija i time se bavi bug #11 .
