### ISSUE TITLE
Ugovor o ucenju - Svi izborni predmeti imaju oznaku AE

### ISSUE THREAD

**Issue by dbrackovic2** [etf-sarajevo/zamger#23]
Bug se desava prilikom kreiranja ugovora o ucenju. U dropdown menijima za odabir predmeta sa drugih odsjeka svi ponudjeni predmeti imaju uz sebe oznaku AE, kao da su svi sa istog odsjeka, automatike i elektronike.

Visual:
https://screenpresso.com/=qF2Ob

**Comment by vljubovic** [comment]
Popravljeno, zahvaljujem.
