### ISSUE TITLE
Bespotreban input koji treba biti hidden

### ISSUE THREAD

**Issue by NedimBadzak** [etf-sarajevo/zamger#52]
Na profil modulu postoji input type="text" koji bi trebao biti hidden (sto govori i njegov class="hidden") medjutim nije.
![image](https://user-images.githubusercontent.com/23142003/141699747-073b23f9-14ec-4a0c-bc3c-96be28cf52b8.png)

Jedno rješenje bi bilo da se stavi type="hidden" ili da se class="hidden" prepravi tako da se postavi display:none.

HTML dio sa tim inputom:
![image](https://user-images.githubusercontent.com/23142003/141699786-4f50edf5-0f96-4a3a-a86f-deb024761d2e.png)

(Da ne forkam samo zbog ovoga, lakse je da postavim issue :smile:  )

**Comment by vljubovic** [comment]
Popravljeno, commit 56285d877a7d83113ed0d68aade39e678ee67d3d
