### ISSUE TITLE
Kreiranje ugovora nije moguce

### ISSUE THREAD

**Issue by arogo1** [etf-sarajevo/zamger#53]
Student sam master studija, smjer RI. Polozio sam sve ispite i ostao mi je magistarski rad, te prilikom kreiranja ugovora nisam u mogucnosti da izaberem predmete(vjerovatno jer sam ih polozio) 
![image](https://user-images.githubusercontent.com/37342503/191212949-e0ad62b2-a8f4-4d04-b02c-8e1f5aed2898.png)
te kada kliknem na opciju kreiraj ugovor dobijem sljedecu gresku 
![image](https://user-images.githubusercontent.com/37342503/191213068-54661879-1132-4936-9e11-63b94257c860.png)

Unaprijed hvala

**Comment by vljubovic** [comment]
Popravljeno 300b1100babd171b65300c1c93575f562551437f
